### ISSUE TITLE
ItemDescription

### ISSUE THREAD

**Issue by ogbanana** [JPlate-Project/JPlate#13]
On the homepage if customer is interested on the plate, they click the cart icon/button on the plate and a box pops up with the item description, the image, the name, price, a quantity selector with + and -. It'll start at 1 plate, the price will increase if use add more plates in the quantity selector. There will be an "add to cart" button on this pop up that will send the items to the cart. There should be an option to X out and not add anything to the cart.

**Comment by mallockey** [comment]
-Added ItemDescription component.
-Added state to display ItemDescription when cart button is clicked.
-Added currentPlate prop to itemdescription.
-Added X button to exit out.

TODO:
-Format entire ItemDescription
-Add +- buttons
-Add amount
-Add quantity
