### ISSUE TITLE
Cart - Due 7/31/20

### ISSUE THREAD

**Issue by ogbanana** [JPlate-Project/JPlate#16]
Takes the data from itemDescription. 
It'll render the item image, the name of item, 30 characters of the description, eg. "This is an aqua plate...". Quantity selector so the customer will be able to add more of that item from the Cart. (Quantity Selector could be it's own component). Total price of each unique plate on the right. Then on the bottom a total price, BEFORE TAX AND SHIPPING, of all the plates together. Checkout button will bring you to checkout page.

**Comment by mallockey** [comment]
Please help me with this.
